engines:
  rubocop:
    enabled: true
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false
  scss-lint:
    enabled: false

ratings:
  paths:
    - app/**
    - lib/**
    - "**.rb"
    - "**.go"

exclude_paths:
  - spec/**/*
  - vendor/**/*
  - config/**/*
